services:
  postgresql:
    image: "postgres:16.0"
    container_name: "todo-list-db"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=todos_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password