services:
  app:
    depends_on:
      - postgresql
    image: "quay.io/yborgess/todo-list-spring-boot-backend:latest"
    container_name: "todo-list-app"
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/todos_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - ORG_DEMO_TODOLIST_CORS_ALLOWED_ORIGINS=*